import TopNavBar from "@/components/TopNavBar";


export const metadata = {
  title: "KHbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <TopNavBar />
      <main>
        {children}
      </main>
    </>
  );
}
