import { Geist, Geist_Mono } from "next/font/google";
import TopNavBar from "@/components/TopNavBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SideNavBar from "@/components/SideNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen flex-col bg-gray-50">
      <TopNavBar />

      <div className="flex flex-1 overflow-hidden border-t">
        <SidebarProvider >
          <aside className="hidden !w-40 flex-col border-r bg-white md:flex">
            <SideNavBar />
          </aside>

          <main className="flex-1 overflow-y-auto p-8">
            <SidebarTrigger className="md:hidden mb-4" />
            {children}
          </main>
        </SidebarProvider>
      </div>
    </div>
  );
}
